name: Java CI with Maven and Tagging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run unit tests
      run: mvn test

    - name: Create Tag
      if: success()  # Only create tag if the build and tests are successful
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        TAG_NAME="v1.0.$(date +%Y%m%d%H%M%S)"
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git tag $TAG_NAME
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
